---
title: "Preben 17.09.18"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r init, message=FALSE, echo = FALSE,include= FALSE}

library(png)
library(readr)
library(ggplot2)
library(dplyr)
library(tidyquant)
library(timetk)
library(tibbletime)

equinor <- read_csv("https://www.netfonds.no/quotes/paperhistory.php?paper=EQNR.OSE&csv_format=csv", 
    col_types = cols(quote_date = col_datetime(format = "%Y%m%d")))

hydro <- read_csv("https://www.netfonds.no/quotes/paperhistory.php?paper=NHY.OSE&csv_format=csv", 
    col_types = cols(quote_date = col_datetime(format = "%Y%m%d")))

combined <- merge(equinor,hydro, by="quote_date")

over_2010 <- filter(combined, quote_date >= "2010-01-01")




```

```{r graphs, echo = FALSE } 




ggplot() + 
  geom_line(data = over_2010, aes(x = quote_date, y = close.x), color = "purple") + 
  geom_line(data = over_2010, aes(x = quote_date, y = close.y), color = "green")  + 
  labs(
        title = "Aesthetically pleasing representation of closing positions for Equinor & Hydro",
        x = "Year",
        y = "Close") +
  
  theme_dark() 
  





```



```{r log_return}

combined$log_return_equinor <- c(diff(log(combined$close.x)),NA)
combined$log_return_hydro <- c(diff(log(combined$close.y)),NA)



ggplot() + 
  geom_line(data = over_2010, aes(x = quote_date, y = log_return_equinor), color = "purple") + 
  geom_line(data = over_2010, aes(x = quote_date, y = log_return_hydro), color = "green")  + 
  labs(
        title = "Aesthetically pleasing representation of logreturns for Equinor & Hydro",
        x = "Year",
        y = "Close") +
  
  theme_dark() 
  

#Source for calculating log
#https://stackoverflow.com/questions/18008355/calculate-daily-log-return-within-a-data-frame
```



  