---
title: "Assignment 6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r init, message=FALSE, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(plyr)


DS = tribble(
 ~fk_account_code, ~Ansvar, ~fk_function_code, ~fk_project_code, ~amount,
 101030,40220,"Det",3432,1493.00,
 101030,40220,"Met",3586,2827.00,
 101030,40320,"Det",3456,49440.00,
 101030,40330,"Sal",NA,870716.00,
 101030,40350,"Met",NA,559928.00,
 101030,40360,"Sal",NA,125534.00,
 101030,40280,"Pol",NA,251611.00)

df <- data.frame(Product=gl(3,10,labels=c("A","B", "C")), 
                Year=factor(rep(2002:2011,3)), 
                Sales=1:30)


```


```{r cleaning, message=FALSE, echo=FALSE}

#Removing fk_project_code
DS <- DS[-4]

#Recoding variables
DS$fk_function_code <- ifelse(DS$fk_function_code == "Det", "supplies", 
                       ifelse(DS$fk_function_code == "Sal", "supplies",
                        ifelse(DS$fk_function_code == "Met", "inventories",
                        ifelse(DS$fk_function_code == "Pol", "other expenses" , NA))))


```


```{r calc, message=FALSE, echo=FALSE}


#Removing the three first digits
DS$Ansvar <- substr(DS$Ansvar, 1, 3)

#Converting the datatype back to numerics
DS$Ansvar <- as.numeric(DS$Ansvar)

#Sum of Ansvar
sum(DS$Ansvar)




#DF calcs
divider <- function(x){
   x/sum(x)
}

df <- ddply(df, "Year", transform, Sales = divider(Sales))


#Source for soultion for calculate the share of sales per product per year.
#https://magesblog.com/post/2012-06-12-transforming-subsets-of-data-in-r-with/

```





```{r graphs}

ggplot() +
  geom_line(data = df, aes ( x = Year, y = Sales, group = Product, color = Product)) +
  theme_classic() +
  labs(
        title = "Shares per year per group",
        x = "Year",
        y = "Shares") 

```

